/* Generated by AN DISI Unibo */ 
package it.unibo.sistemas

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sistemas ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | SistemaS QAK avviato, in ascolto...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForWork", cond=doswitch() )
				}	 
				state("waitForWork") { //this:State
					action { //it:State
						discardMessages = false
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleEval",cond=whenRequest("eval"))
				}	 
				state("handleEval") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("eval(X)"), Term.createTerm("eval(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val X      = payloadArg(0).toDouble()  
								CommUtils.outcyan("$name | eval ricevuto: x=${X}")
								 val Result = Math.sin(X) + Math.cos(Math.sqrt(3.0) * X)  
								CommUtils.outcyan("$name | risultato: ${Result}")
								answer("eval", "evalDone", "evalDone($Result)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForWork", cond=doswitch() )
				}	 
			}
		}
} 
