/* Generated by AN DISI Unibo */ 
package it.unibo.firefly1

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly1 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var shouldSync = false  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | fase 0ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="charging", cond=doswitch() )
				}	 
				state("charging") { //this:State
					action { //it:State
						 shouldSync = false  
						discardMessages = false
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_charging", 
				 	 					  scope, context!!, "local_tout_"+name+"_charging", 1000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="doFlash",cond=whenTimeout("local_tout_"+name+"_charging"))   
					transition(edgeName="t01",targetState="perceiveFlash",cond=whenEvent("flash"))
				}	 
				state("perceiveFlash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("flash(ID)"), Term.createTerm("flash(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 shouldSync = payloadArg(0) != name  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doFlash", cond=doswitchGuarded({ shouldSync  
					}) )
					transition( edgeName="goto",targetState="charging", cond=doswitchGuarded({! ( shouldSync  
					) }) )
				}	 
				state("doFlash") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | *** FLASH! ***")
						emit("flash", "flash(firefly1)" ) 
						discardMessages = true
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="refractory", cond=doswitch() )
				}	 
				state("refractory") { //this:State
					action { //it:State
						delay(200) 
						discardMessages = false
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="charging", cond=doswitch() )
				}	 
			}
		}
} 
