/* Generated by AN DISI Unibo */ 
package it.unibo.lifegame

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Lifegame ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val life = main.java.conway.domain.Life(20,20)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("QActor lifegame | START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitEvents", cond=doswitch() )
				}	 
				state("waitEvents") { //this:State
					action { //it:State
						CommUtils.outblack("QActor lifegame | Esperando comandos...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleStart",cond=whenEvent("start"))
					transition(edgeName="t01",targetState="handleCell",cond=whenEvent("cellstate"))
				}	 
				state("handleStart") { //this:State
					action { //it:State
						CommUtils.outblack("QActor lifegame | Logica per START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitEvents", cond=doswitch() )
				}	 
				state("handleCell") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cellstate(X,Y)"), Term.createTerm("cellstate(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("QActor lifegame | Click en celda: ${payloadArg(0)},${payloadArg(1)}")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitEvents", cond=doswitch() )
				}	 
			}
		}
} 
